### ISSUE TITLE
ODE solver in LTC cells

### ISSUE THREAD

**Issue by sviret** [michaelkhany/liquid_time_constant_networks#3]
Another question. I'm currently trying to adapt LTC4 to Keras3 in order to compare it to legacy LNN code (which is here: https://github.com/mlech26l/ncps/tree/master/ncps/keras).

There is one thing I don't understand in LTC4 code, which is when the ODE solver is used? In the legacy code there is an explicit method defined to do so (https://github.com/mlech26l/ncps/blob/master/ncps/keras/ltc_cell.py#L255), whereas in your code it looks like the solver option is never used by anything. Moreover it's not defined in AbstractRNNCell class, or even in MinimalRNNCell, and changing the ODE_solver value to something different than 0/1/2 doesn't affect the code, I'm able to use the LTCCell while putting solver value to 5 for example, which tends to show that neural state calculation is not using it.

Am I missing something here???

**Comment by michaelkhany** [comment]
Thank you for your input.  You were correct in observing that the initial implementation of the LTCCell uploaded here had an unused solver parameter. In the original code, while the solver option was included in the cell's initialization, it wasn't actually used to influence the neural state updates, effectively making it redundant.

**Revisions Made:**
We have now added the released code which included three different ODE solvers—SemiImplicit, Explicit, and RungeKutta—based on the Liquid Time-Constant Neural Network (LTCN) framework. Each of these solvers provides a unique method for updating the cell's state:
Semi-Implicit Euler Method: This solver performs a semi-implicit update of the neural state, providing a balance between stability and computational efficiency.
Explicit Euler Method: An explicit method that directly uses the activation to update the state, which is simpler but can be less stable for stiff equations.
Fourth-Order Runge-Kutta Method: A more advanced and accurate method that approximates the solution by considering multiple slopes (k1, k2, k3, k4) for a single step.
Integration into call Method: We integrated these solvers into the call method of the LTCCell. Now, the chosen solver option (ODESolver.SemiImplicit, ODESolver.Explicit, or ODESolver.RungeKutta) determines how the cell's state is updated during each time step.

**Comment by sviret** [comment]
Thanks for the reply, it makes things much clearer now

**Comment by sviret** [comment]
BTW, I think there is a typo in the definition of the Explicit and SemiImplicit solver:

https://github.com/michaelkhany/liquid_time_constant_networks/blob/main/LTC4.py#L71

For the step size I suppose one should use 1.0/self._ode_solver_unfolds (as in RK solver)  and not self._ode_solver_unfolds.
